function formatMenuList(menuGroupList) {
    let resultHtml = "<ul>\n";
    menuGroupList.forEach(menuGroup => {
        let tmpHtml = "<li><a href=\"" + menuGroup.url.replace("/", "-") + "\">" + menuGroup.title + "</a></li>";
        if (menuGroup.list.length > 0) {
            tmpHtml += "<ul>\n";
            menuGroup.list.forEach(menuItem => {
                tmpHtml += "<li><a href=\"" + menuItem.url.replace("/", "-") + "\">" + menuItem.title + "</a></li>";
            });
            tmpHtml += "</ul>\n";
        }
        resultHtml += tmpHtml;
    });
    resultHtml += "\n</ul>";
    return resultHtml;
}

function formatMenuHtml(bookTitle, menuInfo) {
    let allGroupHtml = "<div class=\"book-main-title\"><h1>目录</h1></div>";
    allGroupHtml += "<div class='menu-list'>";
    allGroupHtml += formatMenuList(menuInfo);
    allGroupHtml += "</div>";
    return "<!DOCTYPE html>\n" +
        "<html lang=\"en\">\n" +
        "  <head>\n" +
        "    <meta charset=\"utf-8\" />\n" +
        "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n" +
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" />" +
        "    <title>" + bookTitle + "</title>\n" +
        "    <link rel=\"stylesheet\" href=\"../css/menu.css\" />\n" +
        "    <link rel=\"stylesheet\" href=\"../../laravel/css/menu-extra.css\"/>\n" +
        "  </head>\n" +
        "  <body>\n" + allGroupHtml + "\n" +
        "<div class=\"menu-tip\" style=\"margin-top: 0;\"><span>Generated by</span><a href=\"https://github.com/liuguangw/pdf-builder\">pdf-builder</a></div>\n" +
        " </body>\n" +
        "</html>";
}

module.exports = (bookInfo, menuInfo, menuHtmlCallback, errorFn) => {
    let htmlCode = formatMenuHtml(bookInfo.title, menuInfo);
    menuHtmlCallback(htmlCode);
};