function formatMenuHtml(bookTitle, menuInfo) {
    let allGroupHtml = "<h1 class=\"toc-h1\">" + bookTitle + "</h1>\n" +
        "\t<div class=\"toc-main\">\n" +
        "\t<ul>\n" +
        "\t\t<li class=\"toc-group toc-item\">\n" +
        "\t\t\t<ol>\n";
    for (let menuGroupIndex = 0; menuGroupIndex < menuInfo.length; menuGroupIndex++) {
        let pageNode = menuInfo[menuGroupIndex];
        let pageUrl = pageNode.url;
        if (pageUrl === "") {
            pageUrl = "index.html";
        } else {
            pageUrl = pageUrl.substr(0, pageUrl.indexOf("/")) + ".html";
        }
        allGroupHtml += "\t\t\t\t<li class=\"toc-item\"><a href=\"" + pageUrl + "\">" + pageNode.title + "</a></li>\n";
    }
    allGroupHtml += "\t\t\t</ol>\n" +
        "\t\t</li>\n";
    allGroupHtml += "\t</ul>\n\t</div>";
    return "<!DOCTYPE html>\n" +
        "<html lang=\"en\">\n" +
        "  <head>\n" +
        "    <meta charset=\"utf-8\" />\n" +
        "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n" +
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" />" +
        "    <title>" + bookTitle + "</title>\n" +
        "    <link rel=\"stylesheet\" href=\"../css/menu.css\" />" +
        "    <link rel=\"stylesheet\" href=\"../../laravel/css/menu-extra.css\"/>\n" +
        "  </head>\n" +
        "  <body>\n" + allGroupHtml + "\n" +
        "  <div class=\"menu-tip\" style=\"margin-left: 40px;\"><span>Generated by</span><a href=\"https://github.com/liuguangw/pdf-builder\">pdf-builder</a></div>\n" +
        " </body>\n" +
        "</html>";
}

module.exports = (bookInfo, menuInfo, menuHtmlCallback, errorFn) => {
    let htmlCode = formatMenuHtml(bookInfo.title, menuInfo);
    menuHtmlCallback(htmlCode);
};